name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Criterion
      run: sudo apt-get update && sudo apt-get install -y libcriterion-dev pkg-config valgrind

    - name: Install test-tap
      run: npm install -g test-tap

    - name: Build
      run: cmake . -DCMAKE_BUILD_TYPE=Debug && make  # Add build type

    - name: Run Tests
      run: ./test_pointers --tap > test_results.tap

    - name: Convert to JSON
      if: always()
      run: tap-to-json test_results.tap > test_results.json

    - name: Check for Memory Leaks (Optional - using valgrind)
      if: always() # Run even if tests fail (for debugging)
      run: valgrind --leak-check=full ./test_pointers

    - name: AI Tutor in English
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: English
      id: ai-tutor-English
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in Swedish
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: Swedish
      id: ai-tutor-Swedish
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in German
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: German
      id: ai-tutor-German
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in Korean
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: Korean
      id: ai-tutor-Korean
      if: always()
      timeout-minutes: 2

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: |
          test_results.tap
          test_results.json
