name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: "uv"
        cache-dependency-glob: "./requirements.txt"

    - name: Install CMocka and Jansson
      run: sudo apt-get update && sudo apt-get install -y libcmocka-dev libjansson-dev pkg-config valgrind

    - name: Build
      run: cmake . -DCMAKE_BUILD_TYPE=Debug && make

    - name: Run C Tests
      run: ./my_tests

    - name: Run Pytest
      if: always() # Run even if tests fail (for debugging)
      run: |
        source my_env/bin/activate
        pytest --json-report --json-report-indent=4 --json-report-file=test_results.json test/test_pointers.py

    - name: Check for Memory Leaks (Optional - using valgrind)
      if: always() # Run even if tests fail (for debugging)
      run: valgrind --leak-check=full ./my_tests

    - name: AI Tutor in English
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: English
      id: ai-tutor-English
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in Swedish
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: Swedish
      id: ai-tutor-Swedish
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in German
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: German
      id: ai-tutor-German
      if: always()
      timeout-minutes: 2

    - name: AI Tutor in Korean
      uses: kangwonlee/gemini-python-tutor@main
      with:
        report-files: test_results.json
        student-files: src/main.c,src/pointers.c,include/pointers.h
        readme-path: README.md
        api-key: ${{ secrets.GOOGLE_API_KEY }}
        explanation-in: Korean
      id: ai-tutor-Korean
      if: always()
      timeout-minutes: 2

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: test_results.json
