name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Criterion
      run: sudo apt-get update && sudo apt-get install -y libcriterion-dev pkg-config valgrind

    - name: Build
      run: cmake . -DCMAKE_BUILD_TYPE=Debug && make  # Add build type

    - name: Run Tests
      run: ./test_pointers --tap > test_results.tap

    - name: Convert to JSON
      run: tap2json test_results.tap > test_results.json

    - name: Check for Memory Leaks (Optional - using valgrind)
      if: always() # Run even if tests fail (for debugging)
      run: valgrind --leak-check=full ./test_pointers

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test_report.json
