name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Criterion (if needed)
      run: sudo apt-get update && sudo apt-get install -y libcriterion-dev

    - name: Build
      run: cmake . && make

    - name: Run Tests
      run: ./test_pointers
